package hwp.sqlte;

import org.junit.jupiter.api.Test;

import java.lang.reflect.Field;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Tests for {@link ClassInfo} – reflection-based entity metadata.
 */
public class ClassInfoTest {

    // ─── helper entities ─────────────────────────────────────────────────────

    @Table(name = "products")
    static class Product {
        @Id(generate = true)
        public Integer id;
        public String name;
        public Double price;
        @Ignore
        public String ignored;
    }

    /** No @Table – table name is derived from class name. */
    static class DerivedNameEntity {
        @Id
        public Integer id;
        public String value;
    }

    /** Used to test camelCase → underscore column-name mapping. */
    static class UserProfileEntity {
        @Id
        public Integer id;
        public String firstName;
        public String lastName;
    }

    @Table(name = "orders", schema = "sales")
    static class Order {
        @Id
        public Integer id;
        public String status;
    }

    /** No @Id defined – getPKColumn() should throw. */
    static class NoIdEntity {
        public String name;
    }

    /** Used to verify ClassInfo works without @Table. */
    static class SimpleIdEntity {
        @Id
        public Integer id;
        public String description;
    }

    // ─── table name ──────────────────────────────────────────────────────────

    @Test
    void tableName_fromAnnotation() {
        ClassInfo info = ClassInfo.getClassInfo(Product.class);
        assertEquals("products", info.getTableName());
    }

    @Test
    void tableName_derivedFromClass() {
        // No @Table → name derived from simple class name via toUnderscore
        ClassInfo info = ClassInfo.getClassInfo(DerivedNameEntity.class);
        assertEquals("derived_name_entity", info.getTableName());
    }

    @Test
    void tableName_includesSchema() {
        ClassInfo info = ClassInfo.getClassInfo(Order.class);
        assertEquals("sales.orders", info.getTableName());
    }

    // ─── columns ─────────────────────────────────────────────────────────────

    @Test
    void columns_excludesIgnoredFields() {
        ClassInfo info = ClassInfo.getClassInfo(Product.class);
        String[] columns = info.getColumns();
        // id, name, price – NOT "ignored"
        assertEquals(3, columns.length);
        for (String col : columns) {
            assertNotEquals("ignored", col);
        }
    }

    @Test
    void pkColumn_derivedFromAnnotation() {
        ClassInfo info = ClassInfo.getClassInfo(Product.class);
        assertEquals("id", info.getPKColumn());
    }

    @Test
    void insertColumns_excludesAutoGeneratedId() {
        ClassInfo info = ClassInfo.getClassInfo(Product.class);
        for (String col : info.getInsertColumns()) {
            assertNotEquals("id", col, "Auto-generated id must not appear in insert columns");
        }
    }

    @Test
    void updateColumns_excludesPrimaryKey() {
        ClassInfo info = ClassInfo.getClassInfo(Product.class);
        for (String col : info.getUpdateColumns()) {
            assertNotEquals("id", col, "Primary key must not appear in update columns");
        }
    }

    @Test
    void getColumn_camelToUnderscore() {
        ClassInfo info = ClassInfo.getClassInfo(UserProfileEntity.class);
        assertEquals("first_name", info.getColumn("firstName"));
        assertEquals("last_name", info.getColumn("lastName"));
    }

    @Test
    void getFieldByColumn_returnsCorrectField() {
        ClassInfo info = ClassInfo.getClassInfo(Product.class);
        Field field = info.getFieldByColumn("name");
        assertNotNull(field);
        assertEquals("name", field.getName());
    }

    @Test
    void getFieldByColumn_unknownColumn_returnsNull() {
        ClassInfo info = ClassInfo.getClassInfo(Product.class);
        assertNull(info.getFieldByColumn("nonexistent_column"));
    }

    // ─── caching ─────────────────────────────────────────────────────────────

    @Test
    void getClassInfo_returnsSameInstance() {
        ClassInfo a = ClassInfo.getClassInfo(Product.class);
        ClassInfo b = ClassInfo.getClassInfo(Product.class);
        assertSame(a, b, "ClassInfo must be cached – same instance expected");
    }

    // ─── getValueByColumns ───────────────────────────────────────────────────

    @Test
    void getValueByColumns_returnsCorrectValues() {
        Product p = new Product();
        p.id = 42;
        p.name = "Widget";
        p.price = 9.99;

        ClassInfo info = ClassInfo.getClassInfo(Product.class);
        Object[] values = info.getValueByColumns(p, new String[]{"name", "price"});
        assertEquals("Widget", values[0]);
        assertEquals(9.99, values[1]);
    }

    @Test
    void getValueByColumns_emptyArray() {
        Product p = new Product();
        ClassInfo info = ClassInfo.getClassInfo(Product.class);
        Object[] values = info.getValueByColumns(p, new String[0]);
        assertEquals(0, values.length);
    }

    // ─── missing @Id ─────────────────────────────────────────────────────────

    @Test
    void getPKColumn_throwsWhenNoIdDefined() {
        ClassInfo info = ClassInfo.getClassInfo(NoIdEntity.class);
        assertThrows(SqlteException.class, info::getPKColumn);
    }

    // ─── works without @Table ────────────────────────────────────────────────

    @Test
    void classInfoWorksWithoutTableAnnotation() {
        ClassInfo info = ClassInfo.getClassInfo(SimpleIdEntity.class);
        assertNotNull(info.getColumns());
        assertTrue(info.getColumns().length > 0);
    }
}
